language: node_js
node_js:
- '0.10'
install:
- npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: i3lvj+BAxrJfHcbuW2xpDyDJVFW325eoOWdPK7CaMiuX9k5wCcaBr79T7T/xP4s58zvlQ5rx6BnEsYksOiKPauC/dnrutwe/t0SCRkRa8+xIOXqWNKHDkOac9bM1qp+IjR3mwO1vV7pLD7j7UBiXiROi1xIbumNphl3f/xL3rEu+kk64eCRxHoY4vtgHXEh3WLro+8ggWbw0ITKcRnomRiI14m92X9mHfhJc6IIDg3I1+Avcq1ROqvpL3/VxEPAu97UrF9HZyHHwnCQkX0oZNE9adOaN1+ZrR/uOrP1QPKpjWj99p0Xqp9S7YvdS2Ks/6U7HbRDj+mliJjNyjOsQZHB+uTJ05QvkAQD/kZhnK2kp4ddxF9RkKLqa/GqPSQQjBF0U/BXBB30RdVh0AZvOOXY6nvgTHhxoCzCF4mDVeYTbqEsV9pmaqS4Ud1BUy2Z7DEZPtoQAZKdhA263QfqB3Rs6YjL3Fv+v7uviuDjTVrtQHGfldgVbgAUVJlvldff0wEmOs5aQ6ERSVrUqpFaGRfHrOUdGm8aXwHk1A0nJYWbMkWiA+sc4CouBgsYdHnlO5zAuihNWCrdZPYP2FqTDwkCZGTMrlgr06NGFD0Y1fDLS2ZLKdWjb1vH5B6cPNAoIlLBVwIZRBdSnowj/jJhMrJfo15BuDDBlwlt6AgsnJ1E=
  app: ars-uno
  on:
    repo: akhdani/uno
notifications:
  email: false
